# Generated by Django 4.2.6 on 2023-10-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('starting_bid', models.FloatField()),
                ('buyout', models.FloatField()),
                ('reserve_price', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('gun', 'Gun'), ('hull', 'Hull'), ('storage', 'Storage'), ('shield', 'Shield'), ('engine', 'Engine'), ('special', 'Special'), ('fighter drone', 'Fighter Drone'), ('repair drone', 'Repair Drone'), ('harvester', 'Harverster')], max_length=100, null=True)),
                ('item_faction', models.CharField(blank=True, choices=[('human', 'Human'), ('pirate', 'Pirate'), ('heteroclite', 'Heteroclite'), ('wyrd', 'Wyrd'), ('precursor', 'Precursor')], max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_rarity', models.CharField(blank=True, choices=[('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra rare', 'Ultra Rare'), ('elite', 'Elite'), ('legendary', 'Legendary'), ('ultimate', 'Ultimate')], max_length=15, null=True)),
                ('item_rank', models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII'), ('xiii', 'XIII'), ('xiv', 'XIV'), ('xv', 'XV'), ('xvi', 'XVI'), ('xvii', 'XVII'), ('xviii', 'XVIII'), ('xix', 'XIX'), ('xx', 'XX'), ('xxi', 'XXI'), ('xxii', 'XXII'), ('xxiii', 'XXIII'), ('xxiv', 'XXIV'), ('xxv', 'XXV'), ('xxvi', 'XXVI'), ('xxvii', 'XXVII'), ('xxviii', 'XXVIII'), ('xxix', 'XXIX'), ('xxx', 'XXX')], max_length=15, null=True)),
                ('item_quality', models.IntegerField()),
                ('item_durability', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_faction', models.CharField(blank=True, choices=[('human', 'Human'), ('pirate', 'Pirate'), ('heteroclite', 'Heteroclite'), ('wyrd', 'Wyrd'), ('precursor', 'Precursor')], max_length=100, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_elite_ranks', models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V')], max_length=100, null=True)),
                ('ship_durability', models.IntegerField()),
                ('ship_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('time_of_bid', models.DateTimeField(auto_now_add=True)),
                ('auction_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_auction', to='auctions.auction')),
                ('item_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.item')),
                ('ship_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_ship', to='auctions.ship')),
                ('user_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to='auctions.item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_ship', to='auctions.ship'),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_status', to='auctions.auctionstatus'),
        ),
    ]
