# Generated by Django 4.2.7 on 2023-11-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='ship',
        ),
        migrations.AddField(
            model_name='item',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_status', to='auctions.auctionstatus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
